#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-push hook started"
protected_branch='master'

while read local_ref local_sha remote_ref remote_sha
do
    if [ "${remote_ref##refs/heads/}" = "$protected_branch" ]; then
        echo "ERROR: push to $protected_branch is not allowed"
        exit 1
    fi
done

exit 0
